### ISSUE TITLE
Relationship to matrix-ircd

### ISSUE THREAD

**Issue by jplatte** [martinetd/matrirc#1]
Hi! Just wanted to know whether you are aware of [matrix-ircd](https://github.com/matrix-org/matrix-ircd), which was ported to async/await during this year's GSoC (but doesn't use matrix-rust-sdk / Ruma yet). If you are / were aware, what are the reasons you started from scratch?

**Comment by martinetd** [comment]
Hello. Yes I had seen it, but it doesn't support encryption and that was important for me (I tried pantalaimon but couldn't get it to work with purple-matrix previously and just overall got annoyed at the lack of e2ee support everywhere)

the matrix sdk basically gets encryption for free and it was faster for me to start over than try to import this in. Honestly as I wrote in the readme this has been more about learning rust than trying to take over the world -- let's be frank the code is horrible and would need a full refactoring if someone else wants to step in.

If someone has the exact same needs as I do (getting e2ee matrix in irssi) feel free to use it and I'll try to fix things a bit if there are obvious bugs but I really wouldn't want this to take too much of my time in the long run so I'm happy being my sole user & would advise people to use matrix-ircd if they don't need E2EE / want to contribue (the matrix rust sdk has a separate crate for encryption that might be useable on its own)

**Comment by jplatte** [comment]
> the matrix sdk basically gets encryption for free and it was faster for me to start over than try to import this in.

Yeah, for this reason I think it would make a lot of sense to port matrix-ircd over to the SDK.

> I really wouldn't want this to take too much of my time in the long run so I'm happy being my sole user & would advise people to use matrix-ircd if they don't need E2EE / want to contribue

Alright, sounds like I won't be able to convince you to put in any work to merge this with matrix-ircd. Was worth a try ^^

> EDIT: just realized you're the matrix sdk person, who am I telling that :D <-- sleepyhead

Haha, I'm actually not the author of matrix-rust-sdk, that's @poljar. I'm maintaining the libraries the SDK is built on top of ([Ruma](https://github.com/ruma/)) and have contributed a few changes PRs to the SDK, but nothing major :smile:

**Comment by jplatte** [comment]
> I'll probably just add a few polishing commits next week and wrap this up myself, I already switched over.

Now I'm confused. You switched over to what?

**Comment by martinetd** [comment]
Ah, sorry -- just dogfooding, switched from bitlbee with purple-matrix to this (matrirc), not matrix-ircd.

**Comment by jplatte** [comment]
Ah, okay :slightly_smiling_face:

**Comment by martinetd** [comment]
Hi @jplatte -- I see you've archived matrix-ircd a few months ago


It's been a couple of years now and I'll probably keep maintaining this repo (hopefully updating a bit more regularly after this last upgrade/rewrite, but it's not like things stopped working... My only concern with updating too much would be the MRSV of the rust sdk, as that hurts a bit for inclusion in slower distributions like debian, I'll probably stick to the latest commit pre-1.70 for a while.. anyway!)

Would it make sense to advertise this as a possible replacement somewhere?
If I'm lucky I could get people to do some work for me :)

**Comment by martinetd** [comment]
Thanks! Wasn't aware of matrix2051; I was about to say I might have stopped this if I had known about it but it seems to be yet another bridge without e2e encryption so I guess this project still stands...
Well, let's see if I get actual users now :D
