### ISSUE TITLE
Missing tag / release to create proper port

### ISSUE THREAD

**Issue by R-7200** [martinetd/matrirc#16]
Hi!

I'd like to create a port for OpenBSD and NetBSD. matrirc is missing a tag / release, i.e. "milestone" commit, from where I can create a port. I can fork or host a tarball - but I'd like to avoid the hassle and take the official road.

Therefore I'm kindly asking to create a tag, for at least a "0.1" version.

Best wishes.

**Comment by martinetd** [comment]
Thanks for the interest! I've just tagged 1.0 -- might as well start somewhere, and this is already much better than the old v0 branch that has been fully rewritten so I'd rather make it a clear cut.

Please ask again if I messed something up/you need something else
