### ISSUE TITLE
password login has been disabled

### ISSUE THREAD

**Issue by mcepl** [martinetd/matrirc#17]
When trying to register with

```
https://one.element.io mcepl verysecretpassword
```

I get an error `Login failed: the server returned an error: [400 / M_UNKNOWN] Password login has been disabled.. Try again.`

one.element.io server supports only SSO, so `matrirc` should somehow collect and display the URL where I should authenticate.

**Comment by martinetd** [comment]
Interesting, I need to look at how SSO works with the matrix-rust-sdk

A quick look shows the login example now has something about it:
https://github.com/matrix-org/matrix-rust-sdk/blob/72cc2bd60cb7046bb7250c5d09baf3a54f0fbfe4/examples/login/src/main.rs#L49

I don't have any server with sso to test but it doesn't look too bad; our login loop in src/ircd/login.rs (matrix_login_loop) is purely linear so we could update it to `<homeserver> <user> <pass>` or `<homeserver> sso` and follow a different flow based on what's in that example in the later case; if you're interested in trying I'll be happy to review something.
If you can't/don't want implement it, I'm in rather low effort mode on this repo (it's first and foremost just something I use for myself), given it doesn't look too hard to do I might take a stab at it at some point but it probably won't be early enough to be viable for you -- thanks for the heads up though.

**Comment by mcepl** [comment]
I am sorry, I have no clue about Rust at all, being just a stupid Pythonista (who is also currently completely overwhelmed with his actual work).

I tried `sso` with the current code and it doesn’t seem to work:

```
18:56 <matrirc> Welcome to matrirc. Please login to matrix by replying with: <homeserver> <user> <pass>
18:57 <mcepl> https://one.element.io sso
18:57 <matrirc> Message not in <homeserver> <user> <pass> format, ignoring.
```

**Comment by martinetd** [comment]
Yeah, just suggested that as a possible way to implement it, nothing is implemented right now sorry

rust isn't too bad when you're just copying code from one place to another if you can find time to try (and don't run into some annoying compiler errors, the messages usually explain what you need to do clearly enough), and if it builds it'll probably work, so if you can find time to try please do give it a try -- but I'm also painfully aware of how little free time one can have so it's ok if you don't, I'll try to have a look on monday-ish

**Comment by mcepl** [comment]
> rust isn't too bad when you're just copying code from one place to another if you can find time to try (and don't run into some annoying compiler errors, the messages usually explain what you need to do clearly enough), and if it builds it'll probably work, so if you can find time to try please do give it a try -- but I'm also painfully aware of how little free time one can have so it's ok if you don't, I'll try to have a look on monday-ish

That’s the way I was struggling with fixing go-git recently, but really, a day has just so many hours.

**Comment by martinetd** [comment]
I'm glad I didn't say which Monday (what, we're not Monday at all?)
I've tried implementing something in a1de3285ff446c2e1ef13cfbc4ec3257b25d4f32 -- please update & give it a try as I have no account on servers with sso

I've tried on matrix.org and I do get an URL to login but I don't like the way the "redirect URL" points to 127.0.0.1 -- if you don't run matrirc on localhost (from the browser point of view) it is quite unlikely to work:

```
13:27 <matrirc> Welcome to matrirc. Please login to matrix by replying with: <homeserver> [<user> 
                <pass>]
13:27 <testorg> https://matrix.org
13:27 <matrirc> Found server at https://matrix.org; complete connection with one the following:
13:27 <matrirc> reset (start over)
13:27 <matrirc> sso oidc-github
13:27 <matrirc> sso oidc-google
13:27 <matrirc> sso oidc-gitlab
13:27 <matrirc> sso oidc-facebook
13:27 <matrirc> sso oidc-apple
13:27 <matrirc> password <user> <pass>
13:27 <testorg> sso oidc-github
13:27 <matrirc> Login at this URL: 
https://matrix.org/_matrix/client/v3/login/sso/redirect/oidc-github?redirectUrl=http%3A%2F%2F127.0.0.1%3A25257%2F
```
meanwhile:
```
$ ss -nplt | grep 25257
LISTEN 0      1024                  127.0.0.1:25257      0.0.0.0:*    users:(("matrirc",pid=85808,fd=18))       
```

I don't know much about oidc but for something like matrirc I'd rather expect the oidc url to give me a token I could copy-paste back into the chat, and that doesn't look possible with the current code..
(it is however possible to specify something else than 127.0.0.1 to listen to, but I've not implemented that yet as I'm not sure how to present such an option in a way that's not too hard to understand...)

Anyway, if you can try please do and I'll wait to close this; if you need setting a different host/port for the redirect url I'll need to come up with something.

**Comment by mcepl** [comment]
OK, any Monday is good enough for good news, even when it is Tuesday ;).

So, yes, I have managed to connect to one.ems.host and got my (incredibly long) list of channels.

I have initiated verification from the web interface, but I have never found the channel where I could accept it in the IRC client.

However, this particular issue could certainly be closed. Thank you!

**Comment by martinetd** [comment]
Great, thanks for checking!

I'll open a follow-up issue for the bind on localhost callback thing.

> I have initiated verification from the web interface, but I have never found the channel where I could accept it in the IRC client.

Verifications worked for me last I tried (you should get a query from `verif` (or `verif_1` or other suffix if multiple) asking if you accept the verification request then confirming emojis... perhaps that server doesn't support emoji verification either but some new shiny way to verify?
I just checked and don't have appropriate debug logs to investigate this if it doesn't happen but with `RUST_LOG=trace` (very verbose!) you should at least get the event from the matrix side when you initiate the verification

Anyway, please open a new issue for this if you have time to check.
