### ISSUE TITLE
[bug] reopen rooms after restart and restore

### ISSUE THREAD

**Issue by wsdookadr** [martinetd/matrirc#18]
After restarting matrirc, the following messages are shown
```
08:59 <matrirc> Welcome to matrirc. Restoring session to https://matrix.org
08:59 <matrirc> okay
08:59 <matrirc> Finished initial room sync
```

The rooms are not reopened. Trying to reauthenticate by sending `https://matrix.org <user> <password>" generates the error:

```
09:09 -user(user@matrirc)- Could not forward: No such target matrirc
```

**Comment by martinetd** [comment]
I think this is the same as #8

The server currently doesn't actively send JOIN messages for known channels

On my client (irssi), the client just keeps the chans open even if you reconnect so you can just talk there and it works, but on some other clients I'm told they refuse to talk unless you join, so you can't talk there and the channel is only recreated when someone talks first.. Which I agree isn't really practical.
You could just /join yourself but there's no channel list so you'd need to remember the channels and doing it manually isn't exactly good UX

So, yeah, remembering joined channels is something that probably needs to be done; I don't have much time right now but it'll get there eventually.
If you want to help, PRs are welcome as I haven't started.

Closing to move discussions to #8 - feel free to reply here if you disagree
