### ISSUE TITLE
[question] usage with gitter.im

### ISSUE THREAD

**Issue by wsdookadr** [martinetd/matrirc#19]
would it be possible to use matrirc with gitter.im?

**Comment by martinetd** [comment]
I'm not sure what exactly you're asking here.

If you join a gitter.im room through your matrix home server, then it's just a normal room; I'm on one myself and it works fine with matrirc just as it does in element web

If you're talking about using gitter.im as a matrix server directly, I haven't tried; looking at the latest news they say they're running a matrix server now so if it's conformant with the spec (works with third party clients) I assume it'll just work.
One thing that might not work is the login itself, if they don't allow password login, I was just pointed out there's some work needed to support SSO login ( #17 ) - it's probably not too difficult to do but I don't have a server to try, will add some code soonish but I can't promise it'll work.

**Comment by martinetd** [comment]
I've implemented some basic sso and get presented with options to login using `https://gitter.ems.host` as homeserver

I didn't get to try sso until the end (and as said in the other ticket I'm not quite sure what to do about the redirect Url being set to 127.0.0.1), but hopefully that should work if you can work around that problem.

I'm closing this as there is nothing else for me to do here, feel free to reply to the other issue if sso didn't work
