### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by mml** [martinetd/matrirc#6]
This is on Debian 12, upgraded with `rustc 1.66.0+dfsg1-1`.

```
error[E0275]: overflow evaluating the requirement `&tokio::sync::Mutex<vodozemac::olm::session::Session>: std::marker::Send`
    --> src/ircd/mod.rs:79:5
     |
79   |     tokio::spawn(async move {
     |     ^^^^^^^^^^^^
     |
     = help: consider increasing the recursion limit by adding a `#![recursion_limit = "256"]` attribute to your crate (`matrirc`)
note: required because it's used within this `async fn` body
```

Rest of the rather lengthy error elided.  Setting recursion_limit to 256 doesn't fix it.

**Comment by martinetd** [comment]
Hmm,  I remember I had to set a higher recursive limit for older versions of the matrix sdk/rust, so I guess it's something a rust upgrade improved... (I'm running this on nixos unstable, which was on 1.69 at the time I rewrote this v1)

I could reproduce on a debian stable container with the rustc from sid (that sure was a long error!...)
Setting the recursion limit as suggested seems to have fixed it for me (both debug and --release build), where did you try adding it? (it should be in main.rs)

```
diff --git a/src/main.rs b/src/main.rs
index 8bc19db515e6..c6a91c0bff7c 100644
--- a/src/main.rs
+++ b/src/main.rs
@@ -1,3 +1,5 @@
+#![recursion_limit = "256"]
+
 mod args;
 mod ircd;
 mod matrirc;
```

This doesn't seem to have any ill impact on a newer rustc, so I went ahead and commited this; please say if it doesn't work for you.

(Also, yay -- congratulation on opening the first real issue. I guess I'll have to setup a github workflow to at least run clippy and rustfmt at some point..)
